### ISSUE TITLE
Language Not Found

### ISSUE THREAD

**Issue by bbday** [nneonneo/ghidra-wasm-plugin#9]
Language not found for 'Wasm:LE:32:default'
ghidra.program.model.lang.LanguageNotFoundException: Language not found for 'Wasm:LE:32:default'
	at ghidra.program.util.DefaultLanguageService.getLanguage(DefaultLanguageService.java:109)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:333)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2021-Sep-28 1538 EDT
Ghidra Version: 10.0.4
Java Home: C:\Program Files\Java\jdk-17
JVM Version: Oracle Corporation 17
OS: Windows 10 10.0 amd64

**Comment by nneonneo** [comment]
What are the steps to reproduce?

**Comment by bbday** [comment]
> 
> 
> What are the steps to reproduce?

Build Date: 2021-Sep-28 1538 EDT
Ghidra Version: 10.0.4

plugin: **ghidra_10.0.3_PUBLIC_20210927_ghidra-wasm-plugin.zip**

**Comment by canselcik** [comment]
Same issue here with a different *.wasm file.

**Comment by nneonneo** [comment]
The plugin was only released for 10.0.2 and 10.0.3. I've fixed this by releasing v1.0.1: https://github.com/nneonneo/ghidra-wasm-plugin/releases/tag/v1.0.1. This version is built for 10.0.4.

Install the file as an extension; do not unzip the zip file.

**Comment by nneonneo** [comment]
@bbday @canselcik Can you try with the latest release and let me know if the issue is resolved? I believe the problem may be due to upgrading Ghidra without upgrading the underlying plugin, resulting in incompatibility.

**Comment by canselcik** [comment]
Thanks for following up. 

I had already compiled from source into a jar with the `GHIDRA_INSTALL_DIR` pointed to 10.0.4 earlier anyway but I've just tried with the release you linked to and I still seem to be having the same issue.

Granted I am on M1X running Azul JDK so I might not be the best test subject.

```
Java Home: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
JVM Version: Azul Systems, Inc. 17.0.1
OS: Mac OS X 12.0.1 aarch64
```

```
Language not found for 'Wasm:LE:32:default'
ghidra.program.model.lang.LanguageNotFoundException: Language not found for 'Wasm:LE:32:default'
	at ghidra.program.util.DefaultLanguageService.getLanguage(DefaultLanguageService.java:109)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:333)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by nneonneo** [comment]
The JVM version here shouldn't be too much of an issue. If it's not too much trouble, could you specify the steps to reproduce *starting from a clean Ghidra 10.0.4 install*? Hopefully it's just something along the following lines:

1. Unzip the public Ghidra release
2. Launch it and install the extension
3. Restart
4. Create a new project and import a Wasm file

If you're doing something else to trigger this particular bug, I'd love to know.

**Comment by canselcik** [comment]
That's exactly what I am doing. I even nuked `~/.ghidra` just to make sure just now and re-did the entire thing with the same result.

I'd imagine you would have mentioned it already but is there anything I need to manually add `Wasm:LE:32:default` into?

**Comment by nneonneo** [comment]
Under `Installed Processors` you should see Webassembly (the name of the processor is Webassembly, but the ID of the language definition starts with `Wasm:`). If you don't, you may want to check to see if there are any relevant errors in the application log - for example, maybe the SLEIGH definitions didn't compile for some reason.

You could try renaming the processor from `Webassembly` to `Wasm` in `Webassembly.ldefs` and see if that makes a difference - I'd be very surprised if it did, but it's worth a try.

**Comment by canselcik** [comment]
Problem solved. Not sure if immediately attributable to the com.apple.quarantine xattr but everything else was the same:

0- As a last ditch effort run `find . -print0 | xargs -0 xattr -d com.apple.quarantine` on all Ghidra and plugin directories.
1- File > Install Extensions > Install the wasm-plugin ZIP by path
2- Restart ghidra
3- Works, shows up in processor definitions and loads the wasm file fine.

Thanks @nneonneo.

**Comment by bbday** [comment]
> 
> 
> @bbday @canselcik Can you try with the latest release and let me know if the issue is resolved? I believe the problem may be due to upgrading Ghidra without upgrading the underlying plugin, resulting in incompatibility.

For me work. Thanks
